language: python

branches:
  only:
    - master

env:
  - TOXENV=py27-lint
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django110
  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=py35-django110

install:
  - pip install tox

script:
  - tox -e $TOXENV

after_success:
  - pip install codecov
  - codecov -e TOXENV
